import "./hero.css";
import AnimatedText from "../../../../components/animation/AnimatedText";

const Hero = () => {
  return (
    <section className="hero">
      <div className="hero-content">
        <h1 className="hero-heading">
          Invest in Real Estate, Earn Passive Income
        </h1>
        <h2 className="hero-subheading">Unlock the Power of Property Shares</h2>
        <div className="flex flex-1 justify-center mx-auto">
          <AnimatedText />{" "}
        </div>
        <p className="hero-description">
          Own a piece of prime real estate and earn regular dividends. Invest in
          property shares and enjoy the benefits of passive income.
        </p>
        <div className="hero-features">
          <div className="hero-feature">
            <h3 className="feature-heading">Diversify Your Portfolio</h3>
            <p className="feature-description">
              Expand your investment portfolio by buying shares of carefully
              selected rental properties.
            </p>
          </div>
          <div className="hero-feature">
            <h3 className="feature-heading">Steady Dividend Payouts</h3>
            <p className="feature-description">
              Receive regular dividends from the profits generated by our rental
              properties.
            </p>
          </div>
          <div className="hero-feature">
            <h3 className="feature-heading">Simple and Transparent</h3>
            <p className="feature-description">
              Our user-friendly platform makes investing in property shares easy
              and provides transparent information about property performance.
            </p>
          </div>
          <div className="hero-feature">
            <h3 className="feature-heading">Expertly Managed Properties</h3>
            <p className="feature-description">
              Rest assured knowing that our team of experts handles property
              management, ensuring hassle-free investment for you.
            </p>
          </div>
          <div className="hero-feature">
            <h3 className="feature-heading">Invest with Confidence</h3>
            <p className="feature-description">
              With a track record of successful investments, we offer a secure
              and trustworthy platform for your financial goals.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Hero;
