export const STRIPE_PYMT_REQUEST = 'STRIPE_PYMT_REQUEST';
export const STRIPE_PYMT_SUCCESS = 'STRIPE_PYMT_SUCCESS';
export const STRIPE_PYMT_FAIL = 'STRIPE_PYMT_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'; 
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'; 
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE'; 
    